version: "3.7"

services:
  web:
    image: yuya207503/requestinvoice:v0.0.1@sha256:
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - 8809:8809
    volumes:
      - ${LND_DATA_DIR}:/lnd:ro
      - ${APP_DATA_DIR}/data:/data
    environment:
      LND_GRPC_ENDPOINT: $LND_IP
      LND_GRPC_PORT: $LND_GRPC_PORT
      LND_GRPC_CERT: /lnd/tls.cert
      LND_GRPC_MACAROON: /lnd/data/chain/bitcoin/${BITCOIN_NETWORK}/admin.macaroon