version: "3.7"

services:
  web:
    image: yuya207503/requestinvoice:v0.0.1@sha256:75ccdcf5eae455fcc10039d2b3caf7bc37bdc0a534f4eea9839c22b77fc0a333
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - 8809:8809
    environment:
      LND_IP: $LND_IP
      LND_PORT: $LND_GRPC_PORT
      TLS_LOCATION: /lnd/tls.cert
      MACAROON_LOCATION: /lnd/data/chain/bitcoin/${BITCOIN_NETWORK}/admin.macaroon